a_lr: 0.0001
algo: ddpg
batch_size: 64
buffer_size: 100000
c_lr: 0.0001
episode_length: 200
epsilon: 0.5
epsilon_speed: 0.99998
game_name: snakes_3v3
gamma: 0.95
load_model: false
load_model_run: 2
load_model_run_episode: 4000
log_dir: '20211117_120707'
max_episodes: 50000
model_episode: 0
output_activation: softmax
save_interval: 1000
seed: 1
tau: 0.001
